### ISSUE TITLE
ImportError: cannot import name '_C' from partially initialized module 'diff_gaussian_rasterization' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by RisaXieyantong** [Kunhao-Liu/StyleGaussian#3]
Hi! 

当我尝试在conda虚拟环境中运行 python viewer.py -m output/train/artistic/default --style_folder images --viewer_port 8080 命令，报错如下：
```
 Traceback (most recent call last):
  File "viewer.py", line 9, in <module>
    from gaussian_renderer import GaussianModel
  File "D:\00 Style Gaussian\StyleGaussian-main\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "D:\00 Style Gaussian\StyleGaussian-main\submodules\diff-gaussian-rasterization\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: cannot import name '_C' from partially initialized module 'diff_gaussian_rasterization' (most likely due to a circular import) (D:\00 Style Gaussian\StyleGaussian-main\submodules\diff-gaussian-rasterization\diff_gaussian_rasterization\__init__.py)
```
我已将 Visual Studio 的 cl.exe 路径添加到 Conda 创建的虚拟环境的 PATH 变量中，但并没有解决。
报错显示这个问题可能与循环导入有关，但我不确定如何解决。请问你能提供一些指导吗？非常感谢

**Comment by Kunhao-Liu** [comment]
你好，我对Visual Studio的使用不太熟悉哎，我是用的VS code。这个错误可能更多的和Visual Studio的用法有关。
